### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by spleijers** [marconfus/ha-nefit-ng#11]
```
nefit: Error on device update!
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 248, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/app/homeassistant/helpers/entity.py", line 377, in async_device_update
    await self.async_update()
  File "/config/custom_components/nefit/climate.py", line 173, in async_update
    await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```
I always get a TimeoutError, the nefit plugin does not connect at all. 

From home-assistant.log
`
2019-04-01 11:56:43 WARNING (MainThread) [slixmpp.stringprep] Using slower stringprep, consider compiling the faster cython/libidn one.
2019-04-01 11:56:43 DEBUG (MainThread) [aionefit] Initializing XMPP client
2019-04-01 11:56:45 DEBUG (MainThread) [aionefit] Sending msg...GET /ecus/rrc/uiStatus HTTP/1.1\rUser-Agent: NefitEasy\r\r
2019-04-01 11:56:45 DEBUG (MainThread) [aionefit] Sending msg...GET /heatingCircuits/hc1/actualSupplyTemperature HTTP/1.1\rUser-Agent: NefitEasy\r\r
2019-04-01 11:56:45 DEBUG (MainThread) [aionefit] Sending msg...GET /system/sensors/temperatures/outdoor_t1 HTTP/1.1\rUser-Agent: NefitEasy\r\r
2019-04-01 11:56:45 DEBUG (MainThread) [aionefit] Sending msg...GET /system/appliance/systemPressure HTTP/1.1\rUser-Agent: NefitEasy\r\r
2019-04-01 11:56:45 DEBUG (MainThread) [aionefit] Sending msg...GET /ecus/rrc/recordings/yearTotal HTTP/1.1\rUser-Agent: NefitEasy\r\r
2019-04-01 11:56:45 DEBUG (MainThread) [aionefit] headers: ['HTTP/1.0 200 OK', 'Content-Length:  664', 'Content-Type: application/json', 'connection: close', '']
2019-04-01 11:56:45 DEBUG (MainThread) [aionefit] body: *SNIP*
2019-04-01 11:56:46 DEBUG (MainThread) [aionefit] response: {"id":"/ecus/rrc/uiStatus","type":"uiUpdate","recordable":0,"writeable":0,"value":{"CTD":"2019-04-01T11:56:45+01:00 Mo","CTR":"room","UMD":"manual","MMT":"17.0","CPM":"auto","CSP":"7","TOR":"on","TOD":"0","TOT":"18.0","TSP":"17.0","IHT":"18.80","IHS":"ok","DAS":"off","TAS":"off","HMD":"off","ARS":"init","FPA":"off","ESI":"on","BAI":"No","BLE":"false","BBE":"false","BMR":"false","PMR":"false","RS":"off","DHW":"on","HED_EN":"false","HED_DEV":"false","FAH":"false","DOT":"false","HED_DB":""}}
2019-04-01 11:56:52 WARNING (MainThread) [homeassistant.components.climate] Setup of platform nefit is taking over 10 seconds.
2019-04-01 11:56:55 ERROR (MainThread) [homeassistant.components.climate] nefit: Error on device update!
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 248, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/app/homeassistant/helpers/entity.py", line 377, in async_device_update
    await self.async_update()
  File "/config/custom_components/nefit/climate.py", line 173, in async_update
    await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

`

**Comment by SaturnusDJ** [comment]
Ok same here. HA 0.90.0.
Nefit thermostat installed today and connected to internet. Mobile application working.

**Comment by SaturnusDJ** [comment]
Error disappeared yesterday. Realized only today that the information is being served via a climate-entity and not as sensor. Working well. @marconfus contact/tag me if you need beta testing someday.

**Comment by SaturnusDJ** [comment]
Had 350 of these errors this night and morning. If this is happening because the servers are unreachable, then maybe a mechanism is needed to reduce error count.

**Comment by spleijers** [comment]
For me, the script never gets any connection it seems...

It seems to connect and it gets an 200 OK:
```
2019-06-04 11:19:27 DEBUG (MainThread) [aionefit] Sending msg...GET /ecus/rrc/uiStatus HTTP/1.1\rUser-Agent: NefitEasy\r\r
2019-06-04 11:19:27 DEBUG (MainThread) [aionefit] Sending msg...GET /heatingCircuits/hc1/actualSupplyTemperature HTTP/1.1\rUser-Agent: NefitEasy\r\r
2019-06-04 11:19:27 DEBUG (MainThread) [aionefit] Sending msg...GET /system/sensors/temperatures/outdoor_t1 HTTP/1.1\rUser-Agent: NefitEasy\r\r
2019-06-04 11:19:27 DEBUG (MainThread) [aionefit] Sending msg...GET /system/appliance/systemPressure HTTP/1.1\rUser-Agent: NefitEasy\r\r
2019-06-04 11:19:27 DEBUG (MainThread) [aionefit] Sending msg...GET /ecus/rrc/recordings/yearTotal HTTP/1.1\rUser-Agent: NefitEasy\r\r
2019-06-04 11:19:27 DEBUG (MainThread) [aionefit] headers: ['HTTP/1.0 200 OK', 'Content-Length:  664', 'Content-Type: application/json', 'connection: close', '']
2019-06-04 11:19:27 DEBUG (MainThread) [aionefit] body: *REDACTED*
2019-06-04 11:19:27 DEBUG (MainThread) [aionefit] response: {"id":"/ecus/rrc/uiStatus","type":"uiUpdate","recordable":0,"writeable":0,"value":{"CTD":"2019-06-04T11:19:27+01:00 Tu","CTR":"room","UMD":"manual","MMT":"17.5","CPM":"auto","CSP":"13","TOR":"off","TOD":"0","TOT":"17.0","TSP":"17.5","IHT":"22.90","IHS":"ok","DAS":"off","TAS":"off","HMD":"off","ARS":"init","FPA":"off","ESI":"on","BAI":"No","BLE":"false","BBE":"false","BMR":"false","PMR":"false","RS":"off","DHW":"on","HED_EN":"false","HED_DEV":"false","FAH":"false","DOT":"false","HED_DB":""}}
2019-06-04 11:19:33 WARNING (MainThread) [homeassistant.components.climate] Setup of platform nefit is taking over 10 seconds.
```
Then it just does not seems to do anything with it:
```
ERROR (MainThread) [homeassistant.components.climate] nefit: Error on device update!
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 261, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/app/homeassistant/helpers/entity.py", line 375, in async_device_update
    await self.async_update()
  File "/config/custom_components/nefit/climate.py", line 173, in async_update
    await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError() 
```
I also see this error at the start:

```
2019-06-04 11:18:47 WARNING (MainThread) [slixmpp.stringprep] Using slower stringprep, consider compiling the faster cython/libidn one.
2019-06-04 11:18:47 DEBUG (MainThread) [aionefit] Initializing XMPP client
```

Any clue on how to fix this?
