### ISSUE TITLE
Connection lost error

### ISSUE THREAD

**Issue by yellowonblack** [marconfus/ha-nefit-ng#16]
I started to experiment constantly connection lost errors, more specific, when I restart HA everything works fine but  after some random time (hours/days) I receive errors like the one below.
I'm using HA 0.94.1 and the mobile app is working fine.

2019-06-18 14:21:17 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.nefit fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 375, in async_device_update
    await self.async_update()
  File "/config/custom_components/nefit/climate.py", line 170, in async_update
    self._client.get(url)
  File "/usr/local/lib/python3.7/site-packages/aionefit/__init__.py", line 98, in get
    self.xmppclient.send_message(mto=self._to, mbody=msg)
  File "/usr/local/lib/python3.7/site-packages/aionefit/provider/slixmpp_impl.py", line 71, in send_message
    message.stream.send_raw(str_data)
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/xmlstream.py", line 926, in send_raw
    raise NotConnectedError()
slixmpp.xmlstream.xmlstream.NotConnectedError

**Comment by bywilco** [comment]
here same problem after 0.94:
Tue Jun 25 2019 13:14:34 GMT+0200 (Midden-Europese zomertijd)
Platform nefit not ready yet. Retrying in 180 seconds.

**Comment by nielsmaneschijn** [comment]
Maybe something has changed at the Nefit/Bosch side of things? I've noticed www.nefit.nl/mijneasy has changed into a redirect to a dumb product page. Have filed a complaint at their end.

**Comment by nielsmaneschijn** [comment]
They're working on it!

**Comment by TimSoethout** [comment]
Zo te zien is de link veranderd:
https://www.nefit-bosch.nl/producten/mijn-easy
En deze bevat een iframe met deze loginpagina:
https://ohbi-auth.thermotechnology.bosch.com/userpage/nefit/login

**Comment by sbesteman** [comment]
Is there a solution at this moment?

**Comment by nielsmaneschijn** [comment]
Response from Nefit:
"Wij hebben sinds vorige week een nieuwe website en er zitten nog een aantal bugs in. We zijn druk bezig om dit op te lossen en om onze website te optimaliseren. Onze excuses voor het ongemak. De door u genoemde foutmelding hoort inmiddels te zijn verholpen.

Middels de volgende link : https://www.nefit-bosch.nl/producten/nefit-easy hoort u alle benodigde informatie te vinden die u zoekt. De website functioneert het beste op de internetbrowser Modzilla."

What Tim said, basically. :)

Not sure what this means for the plugin, I get loads of errors but at the moment it seems to be online.

**Comment by sbesteman** [comment]
stil get Platform nefit not ready yet

and 

Error doing job: Fatal error on transport TCPTransport
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 827, in uvloop.loop.__uv_stream_on_read_impl
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/xmlstream.py", line 406, in data_received
    self._spawn_event(xml)
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/xmlstream.py", line 970, in _spawn_event
    stanza = self._build_stanza(xml)
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/xmlstream.py", line 951, in _build_stanza
    stanza = stanza_type(self, xml)
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/stanzabase.py", line 1390, in __init__
    ElementBase.__init__(self, xml, parent)
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/stanzabase.py", line 416, in __init__
    if self.setup(xml):
  File "/usr/local/lib/python3.7/site-packages/slixmpp/stanza/stream_features.py", line 27, in setup
    self.values = self.values
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/stanzabase.py", line 615, in _set_stanza_values
    self[full_interface] = value
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/stanzabase.py", line 753, in __setitem__
    lang=lang)
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/stanzabase.py", line 959, in _set_sub_text
    return self._del_sub(name, lang=lang)
  File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/stanzabase.py", line 1040, in _del_sub
    parent = self.xml.find(parent_path)
  File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 299, in find
    return ElementPath.find(self, path, namespaces)
  File "/usr/local/lib/python3.7/xml/etree/ElementPath.py", line 307, in find
    return next(iterfind(elem, path, namespaces), None)
TypeError: 'NoneType' object is not an iterator

**Comment by nielsmaneschijn** [comment]
Subtly different errors here:
(not sure if I'm running the latest version tbh)

Update for climate.heating fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 375, in async_device_update
    await self.async_update()
  File "/config/custom_components/nefit/climate.py", line 170, in async_update
    self._client.get(url)
  File "/config/deps/lib/python3.7/site-packages/aionefit/__init__.py", line 98, in get
    self.xmppclient.send_message(mto=self._to, mbody=msg)
  File "/config/deps/lib/python3.7/site-packages/aionefit/provider/slixmpp_impl.py", line 71, in send_message
    message.stream.send_raw(str_data)
  File "/config/deps/lib/python3.7/site-packages/slixmpp/xmlstream/xmlstream.py", line 927, in send_raw
    raise NotConnectedError()
slixmpp.xmlstream.xmlstream.NotConnectedError

**Comment by sbesteman** [comment]
When looking in the code i see the following url wa2-mz36-qrmzh6.bosch.de. Is this still valid?

**Comment by bywilco** [comment]
its fixed.
https://github.com/marconfus/ha-nefit-ng/issues/17

**Comment by trizz** [comment]
After the fix mentioned by @bywilco it worked for a a few days, however, the last few days I'm only getting timeout exceptions. `Timeout while connecting to Bosch cloud. Retrying in the background.`

**Comment by bywilco** [comment]
@trizz, did you try the new nefti.py code?
i updated too 97.1 and put in the new code and after 2 restarts it works again

**Comment by trizz** [comment]
@bywilco Yes, and it worked for a few days, but now it doesn't, even after ~10 restarts 🙈 .

**Comment by LarsBeugelaar** [comment]
I have the same issue, and it seems to start after my thermostat lost its internet connection for a moment. The thermostat shows this with an icon. On the other hand, when this happens Home Assistant has no internet connection either, as they are behind the same modem. So maybe it is more likely that it is due to a loss of connection between the remote xmpp server and the NefitCore or NefitThermostat.

It seems that the integration does not recover from a loss of internet connection. It just keeps on throwing this error and its now at 500+ and counting in the logs.

Might it be an idea to catch the slixmpp.xmlstream.xmlstream.NotConnectedError in async_update() and call connect()? I don't know if any cleanup is necessary. There seems to be no reconnect or disconnect functionality.

It would be great if I would not have to restart Home Assistant when I lose internet connection for a moment.

Thanks!
