### ISSUE TITLE
Component breaks HA 0.103 

### ISSUE THREAD

**Issue by marklagendijk** [marconfus/ha-nefit-ng#23]
Starting from 0.103 HomeAssistant didn't start up anymore.
Error log:
```
homeassistant_1        | 2019-12-25 13:36:39 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal error: protocol.data_received() call failed.
homeassistant_1        | Traceback (most recent call last):
homeassistant_1        |   File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 816, in _read_ready__data_received
homeassistant_1        |     self._protocol.data_received(data)
homeassistant_1        |   File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/xmlstream.py", line 406, in data_received
homeassistant_1        |     self._spawn_event(xml)
homeassistant_1        |   File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/xmlstream.py", line 970, in _spawn_event
homeassistant_1        |     stanza = self._build_stanza(xml)
homeassistant_1        |   File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/xmlstream.py", line 951, in _build_stanza
homeassistant_1        |     stanza = stanza_type(self, xml)
homeassistant_1        |   File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/stanzabase.py", line 1390, in __init__
homeassistant_1        |     ElementBase.__init__(self, xml, parent)
homeassistant_1        |   File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/stanzabase.py", line 416, in __init__
homeassistant_1        |     if self.setup(xml):
homeassistant_1        |   File "/usr/local/lib/python3.7/site-packages/slixmpp/stanza/stream_features.py", line 27, in setup
homeassistant_1        |     self.values = self.values
homeassistant_1        |   File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/stanzabase.py", line 615, in _set_stanza_values
homeassistant_1        |     self[full_interface] = value
homeassistant_1        |   File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/stanzabase.py", line 753, in __setitem__
homeassistant_1        |     lang=lang)
homeassistant_1        |   File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/stanzabase.py", line 959, in _set_sub_text
homeassistant_1        |     return self._del_sub(name, lang=lang)
homeassistant_1        |   File "/usr/local/lib/python3.7/site-packages/slixmpp/xmlstream/stanzabase.py", line 1040, in _del_sub
homeassistant_1        |     parent = self.xml.find(parent_path)
homeassistant_1        |   File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 299, in find
homeassistant_1        |     return ElementPath.find(self, path, namespaces)
homeassistant_1        |   File "/usr/local/lib/python3.7/xml/etree/ElementPath.py", line 307, in find
homeassistant_1        |     return next(iterfind(elem, path, namespaces), None)
homeassistant_1        | TypeError: 'NoneType' object is not an iterator
homeassistant_1        | 2019-12-25 13:36:39 INFO (MainThread) [slixmpp.xmlstream.xmlstream] connection_lost: (TypeError("'NoneType' object is not an iterator"),)
```
Disabling this component fixed the issue.

**Comment by marconfus** [comment]
It's the same as #6. Sorry there is no known fix...
